apiVersion: v1
kind: Namespace
metadata:
  name: ihelp-splash
---
apiVersion: v1
kind: Service
metadata:
    name: ihelp-splash-router
    namespace: ihelp-splash
spec:
    type: LoadBalancer
    selector:
        app: router
    ports:
    - name: "main"
      nodePort: 30001
      port: 30001
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ihelp-splash-client
  namespace: ihelp-splash
spec:
  ports:
  - name: client-port
    protocol: "TCP"
    port: 8005
    targetPort: 8005
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-splash-router
  namespace: ihelp-splash
spec:
  replicas: 1
  selector:
      matchLabels:
        app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ihelp-nginx-files
          mountPath: /etc/nginx/
      volumes:
      - name: ihelp-nginx-files
        hostPath:
          path: /core/ihelp/ihelp-splash/nginx
          type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-splash-client
  namespace: ihelp-splash
spec:
  replicas: 1
  selector:
      matchLabels:
        app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: node:12
        ports:
        - containerPort: 8005
        command: ["npm"]
        args: ["start"]
        env:
        - name: PORT
          value: "8005"
        workingDir: /core
        volumeMounts:
        - name: ihelp-files
          mountPath: /core
      volumes:
      - name: ihelp-files
        hostPath:
          path: /core/ihelp/ihelp-splash
          type: DirectoryOrCreate
